Am = 1;
Ac = 1;
fc = 200;
fm = 50;
fs = 5000;
t = 0:1/fs:0.1;
kf = 100;
delta_f = (kf*Am);
B = delta_f/fm;
x = Am*cos(2*pi*fm*t);
y = Ac*cos((2*pi*fc*t) + (1/fs)*2*pi*kf*cumsum(x));
subplot(2,1,1);
plot(t,x,'r',t,y,'b--');
legend('Original Signal','Modulated Signal');
title('Frequency Modulation of Signal');
subplot(2,1,2);
phase = unwrap(angle(hilbert(y)));
dem = diff(phase)/((2*pi)*(1/fs));
dem = dem-fc;
dem = [dem,0];
dem = dem/max(abs(dem));
plot(t,dem,'r',t,x,'b--');
legend('Demoudlated Signal','Original Signal');
title("Demodulation");